//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drs.Service.LicProxySvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LicProxySvc.ILicProxySvc")]
    public interface ILicProxySvc {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILicProxySvc/RequestActivation", ReplyAction="http://tempuri.org/ILicProxySvc/RequestActivationResponse")]
        string RequestActivation(string sRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILicProxySvc/RequestActivation", ReplyAction="http://tempuri.org/ILicProxySvc/RequestActivationResponse")]
        System.Threading.Tasks.Task<string> RequestActivationAsync(string sRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILicProxySvcChannel : Drs.Service.LicProxySvc.ILicProxySvc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LicProxySvcClient : System.ServiceModel.ClientBase<Drs.Service.LicProxySvc.ILicProxySvc>, Drs.Service.LicProxySvc.ILicProxySvc {
        
        public LicProxySvcClient() {
        }
        
        public LicProxySvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LicProxySvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LicProxySvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LicProxySvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string RequestActivation(string sRequest) {
            return base.Channel.RequestActivation(sRequest);
        }
        
        public System.Threading.Tasks.Task<string> RequestActivationAsync(string sRequest) {
            return base.Channel.RequestActivationAsync(sRequest);
        }
    }
}
