//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drs.Repository.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResShared {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResShared() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Drs.Repository.Resources.ResShared", typeof(ResShared).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin usuario desde el contexto.
        /// </summary>
        public static string ERROR_NOUSER_FROMCONTEXT {
            get {
                return ResourceManager.GetString("ERROR_NOUSER_FROMCONTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en la recursión: {0}..
        /// </summary>
        public static string ERROR_RECURSION {
            get {
                return ResourceManager.GetString("ERROR_RECURSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        public static string FIELD_DESCRIPTION {
            get {
                return ResourceManager.GetString("FIELD_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuerpo del correo.
        /// </summary>
        public static string FIELD_EMAIL_BODY {
            get {
                return ResourceManager.GetString("FIELD_EMAIL_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de la plantilla.
        /// </summary>
        public static string FIELD_EMAIL_CODE {
            get {
                return ResourceManager.GetString("FIELD_EMAIL_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del remitente.
        /// </summary>
        public static string FIELD_EMAIL_NAME_SENDER {
            get {
                return ResourceManager.GetString("FIELD_EMAIL_NAME_SENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo del remitente.
        /// </summary>
        public static string FIELD_EMAIL_SENDER {
            get {
                return ResourceManager.GetString("FIELD_EMAIL_SENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asunto.
        /// </summary>
        public static string FIELD_EMAIL_SUBJECT {
            get {
                return ResourceManager.GetString("FIELD_EMAIL_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string FIELD_NAME {
            get {
                return ResourceManager.GetString("FIELD_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector.
        /// </summary>
        public static string FIELD_PARENT_ID {
            get {
                return ResourceManager.GetString("FIELD_PARENT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruta del logotipo.
        /// </summary>
        public static string FIELD_PATHLOGO {
            get {
                return ResourceManager.GetString("FIELD_PATHLOGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe tener al menos {2}  y máximo {1} caracteres.
        /// </summary>
        public static string LENGTH_FIELD {
            get {
                return ResourceManager.GetString("LENGTH_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe estar entre {1} y {2}.
        /// </summary>
        public static string LENGTH_NUMERIC_FIELD {
            get {
                return ResourceManager.GetString("LENGTH_NUMERIC_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe tener {1} caracteres.
        /// </summary>
        public static string MAXMINSAME_LENGTH_FIELD {
            get {
                return ResourceManager.GetString("MAXMINSAME_LENGTH_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} es un campo requerido.
        /// </summary>
        public static string REQUIRED_FIELD {
            get {
                return ResourceManager.GetString("REQUIRED_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NA.
        /// </summary>
        public static string TITLE_NOT_APPLICABLE {
            get {
                return ResourceManager.GetString("TITLE_NOT_APPLICABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Seleccione un sector-.
        /// </summary>
        public static string TITLE_SELECT_SECTOR {
            get {
                return ResourceManager.GetString("TITLE_SELECT_SECTOR", resourceCulture);
            }
        }
    }
}
