//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drs.Service.SyncFranchiseSvc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseMessageFc", Namespace="http://schemas.datacontract.org/2004/07/FranchiseChannel.Service.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Drs.Service.SyncFranchiseSvc.ResponseMessageFcUnSync))]
    public partial class ResponseMessageFc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalFilesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasError {
            get {
                return this.HasErrorField;
            }
            set {
                if ((this.HasErrorField.Equals(value) != true)) {
                    this.HasErrorField = value;
                    this.RaisePropertyChanged("HasError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalFiles {
            get {
                return this.TotalFilesField;
            }
            set {
                if ((this.TotalFilesField.Equals(value) != true)) {
                    this.TotalFilesField = value;
                    this.RaisePropertyChanged("TotalFiles");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseMessageFcUnSync", Namespace="http://schemas.datacontract.org/2004/07/FranchiseChannel.Service.Model")]
    [System.SerializableAttribute()]
    public partial class ResponseMessageFcUnSync : Drs.Service.SyncFranchiseSvc.ResponseMessageFc {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Drs.Service.SyncFranchiseSvc.UnSyncFilesModel[] LstFilesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Drs.Service.SyncFranchiseSvc.UnSyncFilesModel[] LstFiles {
            get {
                return this.LstFilesField;
            }
            set {
                if ((object.ReferenceEquals(this.LstFilesField, value) != true)) {
                    this.LstFilesField = value;
                    this.RaisePropertyChanged("LstFiles");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnSyncFilesModel", Namespace="http://schemas.datacontract.org/2004/07/FranchiseChannel.Service.Model")]
    [System.SerializableAttribute()]
    public partial class UnSyncFilesModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CheckSumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CheckSum {
            get {
                return this.CheckSumField;
            }
            set {
                if ((object.ReferenceEquals(this.CheckSumField, value) != true)) {
                    this.CheckSumField = value;
                    this.RaisePropertyChanged("CheckSum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SyncFranchiseSvc.ISyncFranchise")]
    public interface ISyncFranchise {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncFranchise/QueryForFiles", ReplyAction="http://tempuri.org/ISyncFranchise/QueryForFilesResponse")]
        Drs.Service.SyncFranchiseSvc.ResponseMessageFc QueryForFiles(System.Guid uidVersion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncFranchise/QueryForFiles", ReplyAction="http://tempuri.org/ISyncFranchise/QueryForFilesResponse")]
        System.Threading.Tasks.Task<Drs.Service.SyncFranchiseSvc.ResponseMessageFc> QueryForFilesAsync(System.Guid uidVersion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncFranchise/GetUnSyncListOfFiles", ReplyAction="http://tempuri.org/ISyncFranchise/GetUnSyncListOfFilesResponse")]
        Drs.Service.SyncFranchiseSvc.ResponseMessageFcUnSync GetUnSyncListOfFiles(System.Guid uidVersion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncFranchise/GetUnSyncListOfFiles", ReplyAction="http://tempuri.org/ISyncFranchise/GetUnSyncListOfFilesResponse")]
        System.Threading.Tasks.Task<Drs.Service.SyncFranchiseSvc.ResponseMessageFcUnSync> GetUnSyncListOfFilesAsync(System.Guid uidVersion);
        
        // CODEGEN: Generating message contract since the wrapper name (RequestMessageFileSync) of message RequestMessageFileSync does not match the default value (GetFileByName)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncFranchise/GetFileByName", ReplyAction="http://tempuri.org/ISyncFranchise/GetFileByNameResponse")]
        Drs.Service.SyncFranchiseSvc.ResponseMessageFileSync GetFileByName(Drs.Service.SyncFranchiseSvc.RequestMessageFileSync request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyncFranchise/GetFileByName", ReplyAction="http://tempuri.org/ISyncFranchise/GetFileByNameResponse")]
        System.Threading.Tasks.Task<Drs.Service.SyncFranchiseSvc.ResponseMessageFileSync> GetFileByNameAsync(Drs.Service.SyncFranchiseSvc.RequestMessageFileSync request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RequestMessageFileSync", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RequestMessageFileSync {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string FileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.Guid UidVersion;
        
        public RequestMessageFileSync() {
        }
        
        public RequestMessageFileSync(string FileName, System.Guid UidVersion) {
            this.FileName = FileName;
            this.UidVersion = UidVersion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResponseMessageFileSync", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ResponseMessageFileSync {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public bool HasError;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string Message;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream File;
        
        public ResponseMessageFileSync() {
        }
        
        public ResponseMessageFileSync(bool HasError, string Message, System.IO.Stream File) {
            this.HasError = HasError;
            this.Message = Message;
            this.File = File;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISyncFranchiseChannel : Drs.Service.SyncFranchiseSvc.ISyncFranchise, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SyncFranchiseClient : System.ServiceModel.ClientBase<Drs.Service.SyncFranchiseSvc.ISyncFranchise>, Drs.Service.SyncFranchiseSvc.ISyncFranchise {
        
        public SyncFranchiseClient() {
        }
        
        public SyncFranchiseClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SyncFranchiseClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SyncFranchiseClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SyncFranchiseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Drs.Service.SyncFranchiseSvc.ResponseMessageFc QueryForFiles(System.Guid uidVersion) {
            return base.Channel.QueryForFiles(uidVersion);
        }
        
        public System.Threading.Tasks.Task<Drs.Service.SyncFranchiseSvc.ResponseMessageFc> QueryForFilesAsync(System.Guid uidVersion) {
            return base.Channel.QueryForFilesAsync(uidVersion);
        }
        
        public Drs.Service.SyncFranchiseSvc.ResponseMessageFcUnSync GetUnSyncListOfFiles(System.Guid uidVersion) {
            return base.Channel.GetUnSyncListOfFiles(uidVersion);
        }
        
        public System.Threading.Tasks.Task<Drs.Service.SyncFranchiseSvc.ResponseMessageFcUnSync> GetUnSyncListOfFilesAsync(System.Guid uidVersion) {
            return base.Channel.GetUnSyncListOfFilesAsync(uidVersion);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Drs.Service.SyncFranchiseSvc.ResponseMessageFileSync Drs.Service.SyncFranchiseSvc.ISyncFranchise.GetFileByName(Drs.Service.SyncFranchiseSvc.RequestMessageFileSync request) {
            return base.Channel.GetFileByName(request);
        }
        
        public bool GetFileByName(string FileName, System.Guid UidVersion, out string Message, out System.IO.Stream File) {
            Drs.Service.SyncFranchiseSvc.RequestMessageFileSync inValue = new Drs.Service.SyncFranchiseSvc.RequestMessageFileSync();
            inValue.FileName = FileName;
            inValue.UidVersion = UidVersion;
            Drs.Service.SyncFranchiseSvc.ResponseMessageFileSync retVal = ((Drs.Service.SyncFranchiseSvc.ISyncFranchise)(this)).GetFileByName(inValue);
            Message = retVal.Message;
            File = retVal.File;
            return retVal.HasError;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Drs.Service.SyncFranchiseSvc.ResponseMessageFileSync> Drs.Service.SyncFranchiseSvc.ISyncFranchise.GetFileByNameAsync(Drs.Service.SyncFranchiseSvc.RequestMessageFileSync request) {
            return base.Channel.GetFileByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<Drs.Service.SyncFranchiseSvc.ResponseMessageFileSync> GetFileByNameAsync(string FileName, System.Guid UidVersion) {
            Drs.Service.SyncFranchiseSvc.RequestMessageFileSync inValue = new Drs.Service.SyncFranchiseSvc.RequestMessageFileSync();
            inValue.FileName = FileName;
            inValue.UidVersion = UidVersion;
            return ((Drs.Service.SyncFranchiseSvc.ISyncFranchise)(this)).GetFileByNameAsync(inValue);
        }
    }
}
