//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drs.ViewModel.SettingSvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SettingSvc.ISettingSvc")]
    public interface ISettingSvc {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISettingSvc/FindAllSettings", ReplyAction="http://tempuri.org/ISettingSvc/FindAllSettingsResponse")]
        Drs.Model.Settings.ResponseMessageSetting FindAllSettings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISettingSvc/FindAllSettings", ReplyAction="http://tempuri.org/ISettingSvc/FindAllSettingsResponse")]
        System.Threading.Tasks.Task<Drs.Model.Settings.ResponseMessageSetting> FindAllSettingsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISettingSvc/FindAllControlTitlesByLanguage", ReplyAction="http://tempuri.org/ISettingSvc/FindAllControlTitlesByLanguageResponse")]
        Drs.Model.Settings.ResponseMessageSetting FindAllControlTitlesByLanguage(int iLanguageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISettingSvc/FindAllControlTitlesByLanguage", ReplyAction="http://tempuri.org/ISettingSvc/FindAllControlTitlesByLanguageResponse")]
        System.Threading.Tasks.Task<Drs.Model.Settings.ResponseMessageSetting> FindAllControlTitlesByLanguageAsync(int iLanguageId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISettingSvcChannel : Drs.ViewModel.SettingSvc.ISettingSvc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SettingSvcClient : System.ServiceModel.ClientBase<Drs.ViewModel.SettingSvc.ISettingSvc>, Drs.ViewModel.SettingSvc.ISettingSvc {
        
        public SettingSvcClient() {
        }
        
        public SettingSvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SettingSvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SettingSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SettingSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Drs.Model.Settings.ResponseMessageSetting FindAllSettings() {
            return base.Channel.FindAllSettings();
        }
        
        public System.Threading.Tasks.Task<Drs.Model.Settings.ResponseMessageSetting> FindAllSettingsAsync() {
            return base.Channel.FindAllSettingsAsync();
        }
        
        public Drs.Model.Settings.ResponseMessageSetting FindAllControlTitlesByLanguage(int iLanguageId) {
            return base.Channel.FindAllControlTitlesByLanguage(iLanguageId);
        }
        
        public System.Threading.Tasks.Task<Drs.Model.Settings.ResponseMessageSetting> FindAllControlTitlesByLanguageAsync(int iLanguageId) {
            return base.Channel.FindAllControlTitlesByLanguageAsync(iLanguageId);
        }
    }
}
