//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralManagement.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResShared {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResShared() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CentralManagement.Resources.ResShared", typeof(ResShared).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string BUTTON_CANCEL {
            get {
                return ResourceManager.GetString("BUTTON_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacto.
        /// </summary>
        public static string BUTTON_CONTACT {
            get {
                return ResourceManager.GetString("BUTTON_CONTACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizar.
        /// </summary>
        public static string BUTTON_END {
            get {
                return ResourceManager.GetString("BUTTON_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string BUTTON_HOME {
            get {
                return ResourceManager.GetString("BUTTON_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        public static string BUTTON_OK {
            get {
                return ResourceManager.GetString("BUTTON_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADQUIRIR.
        /// </summary>
        public static string BUTTON_PACKAGE_BUY {
            get {
                return ResourceManager.GetString("BUTTON_PACKAGE_BUY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRUEBA GRATIS.
        /// </summary>
        public static string BUTTON_PACKAGE_TRIAL {
            get {
                return ResourceManager.GetString("BUTTON_PACKAGE_TRIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reintentar.
        /// </summary>
        public static string BUTTON_RETRY {
            get {
                return ResourceManager.GetString("BUTTON_RETRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regresar.
        /// </summary>
        public static string BUTTON_RETURN {
            get {
                return ResourceManager.GetString("BUTTON_RETURN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string BUTTON_SAVE {
            get {
                return ResourceManager.GetString("BUTTON_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tamaño del archivo no debe ser mayor a {0} bytes. Por favor elija un archivo de menor tamaño..
        /// </summary>
        public static string ERROR_IMAGE_SIZE_TOOLONG {
            get {
                return ResourceManager.GetString("ERROR_IMAGE_SIZE_TOOLONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe uno o más campos inválidos. Por favor revise sus datos e intente de nuevo..
        /// </summary>
        public static string ERROR_INVALID_MODEL {
            get {
                return ResourceManager.GetString("ERROR_INVALID_MODEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe uno o más campos inválidos. &lt;br/&gt;Por favor revise sus datos e intente de nuevo..
        /// </summary>
        public static string ERROR_INVALID_MODEL_HTML {
            get {
                return ResourceManager.GetString("ERROR_INVALID_MODEL_HTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usted no tiene permisos para realizar esta acción o el emisor ya no está activo.
        /// </summary>
        public static string ERROR_LOGO_ISSUER_NOTFOUND {
            get {
                return ResourceManager.GetString("ERROR_LOGO_ISSUER_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No está autorizado para realizar esta acción.
        /// </summary>
        public static string ERROR_MESSAGE_NOT_AUTHORIZED {
            get {
                return ResourceManager.GetString("ERROR_MESSAGE_NOT_AUTHORIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró el registro a eliminar. &lt;br/&gt; Por favor actualice la información e intente de nuevo la operación..
        /// </summary>
        public static string ERROR_MODEL_NOTFOUND {
            get {
                return ResourceManager.GetString("ERROR_MODEL_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El paquete al que pertenece el emisor no tiene el servicio adicional de establecer logotipo en representación impresa.
        /// </summary>
        public static string ERROR_NO_PERMISSION_UPLOADFILE {
            get {
                return ResourceManager.GetString("ERROR_NO_PERMISSION_UPLOADFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La extensión del archivo no pertence a una imagen. Por favor elija otro archivo..
        /// </summary>
        public static string ERROR_NOT_IMAGEFILE {
            get {
                return ResourceManager.GetString("ERROR_NOT_IMAGEFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se sucitó un problema de red. Por favor revise que esté conectado a Internet e intente de nuevo..
        /// </summary>
        public static string ERROR_NOT_NETWORK {
            get {
                return ResourceManager.GetString("ERROR_NOT_NETWORK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su sesión ha caducado, por favor ingrese de nuevo e intente de nuevo.
        /// </summary>
        public static string ERROR_NOT_SESION_ONACTION {
            get {
                return ResourceManager.GetString("ERROR_NOT_SESION_ONACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay archivos que subir o es más de un archivo. Por favor intente de nuevo la operación.
        /// </summary>
        public static string ERROR_NOTSINGLE_FILEFOUND {
            get {
                return ResourceManager.GetString("ERROR_NOTSINGLE_FILEFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puede cambiar un sector con subsectores activos.
        /// </summary>
        public static string ERROR_SECTOR_FAILED {
            get {
                return ResourceManager.GetString("ERROR_SECTOR_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error asignando sector.
        /// </summary>
        public static string ERROR_SECTOR_ITSELF {
            get {
                return ResourceManager.GetString("ERROR_SECTOR_ITSELF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede poner obsoleto el elemento seleccionado, revise que no tenga elementos dependientes.
        /// </summary>
        public static string ERROR_SECTOR_OBSOLETE_FAILED {
            get {
                return ResourceManager.GetString("ERROR_SECTOR_OBSOLETE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error desconocido. .
        /// </summary>
        public static string ERROR_UNKOWN {
            get {
                return ResourceManager.GetString("ERROR_UNKOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sólo es posible añadir un imagen a la vez.
        /// </summary>
        public static string ERROR_UPLOAD_NOSINGLEIMAGE {
            get {
                return ResourceManager.GetString("ERROR_UPLOAD_NOSINGLEIMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se sucitó un error inesperado al subir el archivo. Por favor vuelva a intentar la operación..
        /// </summary>
        public static string ERROR_UPLOADFILE_UNKNOW_ERROR {
            get {
                return ResourceManager.GetString("ERROR_UPLOADFILE_UNKNOW_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro fue guardado de forma exitosa.
        /// </summary>
        public static string INFO_REGISTER_SAVED {
            get {
                return ResourceManager.GetString("INFO_REGISTER_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitud mínima {2}  y longitud máxima {1}.
        /// </summary>
        public static string LENGTH_FIELD {
            get {
                return ResourceManager.GetString("LENGTH_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se presento el siguiente problema al intentar cancelar el documento : {0}.
        /// </summary>
        public static string MSG_ERROR_CANCEL_DOC {
            get {
                return ResourceManager.GetString("MSG_ERROR_CANCEL_DOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha presentado un problema al intentar cancelar el documento.
        /// </summary>
        public static string MSG_ERROR_CANCEL_DOC_GENERAL {
            get {
                return ResourceManager.GetString("MSG_ERROR_CANCEL_DOC_GENERAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} es un campo requerido.
        /// </summary>
        public static string REQUIRED_FIELD {
            get {
                return ResourceManager.GetString("REQUIRED_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asistencia Telefónica.
        /// </summary>
        public static string TITLE_ADICIONAL_SERVICES {
            get {
                return ResourceManager.GetString("TITLE_ADICIONAL_SERVICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuar.
        /// </summary>
        public static string TITLE_BUTTON_CONTINUE {
            get {
                return ResourceManager.GetString("TITLE_BUTTON_CONTINUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to día.
        /// </summary>
        public static string TITLE_DAY {
            get {
                return ResourceManager.GetString("TITLE_DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to días.
        /// </summary>
        public static string TITLE_DAYS {
            get {
                return ResourceManager.GetString("TITLE_DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al cancelar el docuemento.
        /// </summary>
        public static string TITLE_ERROR_CANCEL_DOC {
            get {
                return ResourceManager.GetString("TITLE_ERROR_CANCEL_DOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He leído el aviso de privacidad.
        /// </summary>
        public static string TITLE_HADREAD_PRIVACYNOTICE {
            get {
                return ResourceManager.GetString("TITLE_HADREAD_PRIVACYNOTICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He leído y acepto los términos y condiciones del servicio.
        /// </summary>
        public static string TITLE_HADREAD_SERVICETERMS {
            get {
                return ResourceManager.GetString("TITLE_HADREAD_SERVICETERMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenciamiento.
        /// </summary>
        public static string TITLE_LICENCE {
            get {
                return ResourceManager.GetString("TITLE_LICENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar.
        /// </summary>
        public static string TITLE_LOGIN {
            get {
                return ResourceManager.GetString("TITLE_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar sesión.
        /// </summary>
        public static string TITLE_LOGOFF {
            get {
                return ResourceManager.GetString("TITLE_LOGOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string TITLE_MENU_AUTH {
            get {
                return ResourceManager.GetString("TITLE_MENU_AUTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorizar.
        /// </summary>
        public static string TITLE_MENU_AUTH_ALLOW {
            get {
                return ResourceManager.GetString("TITLE_MENU_AUTH_ALLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicios adicionales.
        /// </summary>
        public static string TITLE_MENU_AUTH_SERVICES {
            get {
                return ResourceManager.GetString("TITLE_MENU_AUTH_SERVICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adquirir paquete.
        /// </summary>
        public static string TITLE_MENU_BUYPACKAGES {
            get {
                return ResourceManager.GetString("TITLE_MENU_BUYPACKAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catálogo de categorías.
        /// </summary>
        public static string TITLE_MENU_CAT_CATEGORIES {
            get {
                return ResourceManager.GetString("TITLE_MENU_CAT_CATEGORIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catálogo de sectores.
        /// </summary>
        public static string TITLE_MENU_CAT_SECTOR {
            get {
                return ResourceManager.GetString("TITLE_MENU_CAT_SECTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración.
        /// </summary>
        public static string TITLE_MENU_CONFIGURATION {
            get {
                return ResourceManager.GetString("TITLE_MENU_CONFIGURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacto.
        /// </summary>
        public static string TITLE_MENU_CONTACT {
            get {
                return ResourceManager.GetString("TITLE_MENU_CONTACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentos emitidos.
        /// </summary>
        public static string TITLE_MENU_DOCUMENT_ISSUED {
            get {
                return ResourceManager.GetString("TITLE_MENU_DOCUMENT_ISSUED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentos.
        /// </summary>
        public static string TITLE_MENU_DOCUMENTS {
            get {
                return ResourceManager.GetString("TITLE_MENU_DOCUMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidades de medida.
        /// </summary>
        public static string TITLE_MENU_MEASURE_UNIT {
            get {
                return ResourceManager.GetString("TITLE_MENU_MEASURE_UNIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mis documentos emitidos.
        /// </summary>
        public static string TITLE_MENU_MY_ISSUED_DOCUMENTS {
            get {
                return ResourceManager.GetString("TITLE_MENU_MY_ISSUED_DOCUMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paquetes.
        /// </summary>
        public static string TITLE_MENU_PACKAGE {
            get {
                return ResourceManager.GetString("TITLE_MENU_PACKAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plantillas de correos.
        /// </summary>
        public static string TITLE_MENU_TEMPLATE_EMAIL {
            get {
                return ResourceManager.GetString("TITLE_MENU_TEMPLATE_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi Cuenta.
        /// </summary>
        public static string TITLE_MY_ACCOUNT {
            get {
                return ResourceManager.GetString("TITLE_MY_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NA.
        /// </summary>
        public static string TITLE_NA {
            get {
                return ResourceManager.GetString("TITLE_NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrado fallido.
        /// </summary>
        public static string TITLE_OBSOLETE_FAILED {
            get {
                return ResourceManager.GetString("TITLE_OBSOLETE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrado exitoso.
        /// </summary>
        public static string TITLE_OBSOLETE_SUCCESS {
            get {
                return ResourceManager.GetString("TITLE_OBSOLETE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio.
        /// </summary>
        public static string TITLE_PRICE {
            get {
                return ResourceManager.GetString("TITLE_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procesando su petición....
        /// </summary>
        public static string TITLE_PROCESSING {
            get {
                return ResourceManager.GetString("TITLE_PROCESSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro fallido.
        /// </summary>
        public static string TITLE_REGISTER_FAILED {
            get {
                return ResourceManager.GetString("TITLE_REGISTER_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro exitoso.
        /// </summary>
        public static string TITLE_REGISTER_SUCCESS {
            get {
                return ResourceManager.GetString("TITLE_REGISTER_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentos.
        /// </summary>
        public static string TITLE_TOTAL_DOCUMENTS {
            get {
                return ResourceManager.GetString("TITLE_TOTAL_DOCUMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emisores.
        /// </summary>
        public static string TITLE_TOTAL_ISSUERS {
            get {
                return ResourceManager.GetString("TITLE_TOTAL_ISSUERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilimitado.
        /// </summary>
        public static string TITLE_UNLIMITED {
            get {
                return ResourceManager.GetString("TITLE_UNLIMITED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logotipo de la representación impresa.
        /// </summary>
        public static string TITLE_UPLOAD_LOGO {
            get {
                return ResourceManager.GetString("TITLE_UPLOAD_LOGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vigencia.
        /// </summary>
        public static string TITLE_VALID_DAYS {
            get {
                return ResourceManager.GetString("TITLE_VALID_DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido.
        /// </summary>
        public static string TITLE_WELCOME {
            get {
                return ResourceManager.GetString("TITLE_WELCOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catálogos.
        /// </summary>
        public static string TITTLE_MENU_CATALOGS {
            get {
                return ResourceManager.GetString("TITTLE_MENU_CATALOGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Quiénes somos?.
        /// </summary>
        public static string TITTLE_MENU_WHO_WE_ARE {
            get {
                return ResourceManager.GetString("TITTLE_MENU_WHO_WE_ARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adquirir paquetes.
        /// </summary>
        public static string TTILE_MENU_BUYPACKAGE {
            get {
                return ResourceManager.GetString("TTILE_MENU_BUYPACKAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emisores.
        /// </summary>
        public static string TTILE_MENU_CATISSUERS {
            get {
                return ResourceManager.GetString("TTILE_MENU_CATISSUERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes.
        /// </summary>
        public static string TTILE_MENU_CATRECEIVERS {
            get {
                return ResourceManager.GetString("TTILE_MENU_CATRECEIVERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mis emisores.
        /// </summary>
        public static string TTILE_MENU_MYISSUERS {
            get {
                return ResourceManager.GetString("TTILE_MENU_MYISSUERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mis paquetes.
        /// </summary>
        public static string TTILE_MENU_MYPACKAGES {
            get {
                return ResourceManager.GetString("TTILE_MENU_MYPACKAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mis clientes.
        /// </summary>
        public static string TTILE_MENU_MYRECEIVERS {
            get {
                return ResourceManager.GetString("TTILE_MENU_MYRECEIVERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparativa de precios.
        /// </summary>
        public static string TTILE_MENU_PRICE_COMPARATIVE {
            get {
                return ResourceManager.GetString("TTILE_MENU_PRICE_COMPARATIVE", resourceCulture);
            }
        }
    }
}
