--SET IDENTITY_INSERT REGIONB ON
/*
BEGIN TRANSACTION

BEGIN TRY
--SET IDENTITY_INSERT REGIONC ON
--DBCC CHECKIDENT('REGIONC', RESEED, 0)

BULK INSERT ViewLocation
FROM 'C:\Projects\SHS\DeliveryReactiveSystem\Docs\localidades.csv'
WITH
(
	FIELDTERMINATOR = '|',
	ROWTERMINATOR = '\n',
	CODEPAGE = 'ACP'
)


COMMIT TRANSACTION
END TRY
BEGIN CATCH
ROLLBACK TRANSACTION
END CATCH
*/
/*
DELETE FROM REGIONC
DELETE FROM ZIPCODE
*/
--SET IDENTITY_INSERT REGIONC OFF
--SET IDENTITY_INSERT REGIONB OFF

--SELECT * FROM ZipCode

--INSERT INTO ZipCode (Code)
--SELECT DISTINCT Code FROM RegionC ORDER BY Code

--SELECT COUNT(*) FROM RegionC

/*
UPDATE R SET R.ZipCodeId = Z.ZipCodeId
FROM ZipCode Z
INNER JOIN RegionC R ON R.Code = Z.Code
*/
