INSERT INTO country (name, Abbreviation, Description) VALUES
('Mexico', 'MX', 'MEX'),
('Afghanistan', 'AF', 'AFG'),
('Albania', 'AL', 'ALB'),
('Antarctica', 'AQ', 'ATA'),
('Algeria', 'DZ', 'DZA'),
('American Samoa', 'AS', 'ASM'),
('Andorra', 'AD', 'AND'),
('Anla', 'AO', 'A'),
('Antigua and Barbuda', 'AG', 'ATG'),
('Azerbaija', 'AZ', 'AZE'),
('Argentina', 'AR', 'ARG'),
('Australia', 'AU', 'AUS'),
('Austria', 'AT', 'AUT'),
('Bahamas', 'BS', 'BHS'),
('Bahrai', 'BH', 'BHR'),
('Bangladesh', 'BD', 'BGD'),
('Armenia', 'AM', 'ARM'),
('Barbados', 'BB', 'BRB'),
('Belgium', 'BE', 'BEL'),
('Bermuda', 'BM', 'BMU'),
('Bhuta', 'BT', 'BT'),
('Bolivia, Plurinational State of', 'BO', 'BOL'),
('Bosnia and Herzevina', 'BA', 'BIH'),
('Botswana', 'BW', 'BWA'),
('Bouvet Island', 'BV', 'BVT'),
('Brazil', 'BR', 'BRA'),
('Belize', 'BZ', 'BLZ'),
('British Indian Ocean Territory', 'IO', 'IOT'),
('Solomon Islands', 'SB', 'SLB'),
('Virgin Islands, British', 'VG', 'VGB'),
('Brunei Darussalam', 'B', 'BR'),
('Bulgaria', 'BG', 'BGR'),
('Myanmar', 'MM', 'MMR'),
('Burundi', 'BI', 'BDI'),
('Belarus', 'BY', 'BLR'),
('Cambodia', 'KH', 'KHM'),
('Cameroo', 'CM', 'CMR'),
('Canada', 'CA', 'CA'),
('Cape Verde', 'CV', 'CPV'),
('Cayman Islands', 'KY', 'CYM'),
('Central African Republic', 'CF', 'CAF'),
('Sri Lanka', 'LK', 'LKA'),
('Chad', 'TD', 'TCD'),
('Chile', 'CL', 'CHL'),
('China', 'C', 'CH'),
('Taiwan, Province of China', 'TW', 'TW'),
('Christmas Island', 'CX', 'CXR'),
('Cocos (Keeling) Islands', 'CC', 'CCK'),
('Colombia', 'CO', 'COL'),
('Comoros', 'KM', 'COM'),
('Mayotte', 'YT', 'MYT'),
('Co', 'CG', 'COG'),
('Con, the Democratic Republic of the', 'CD', 'COD'),
('Cook Islands', 'CK', 'COK'),
('Costa Rica', 'CR', 'CRI'),
('Croatia', 'HR', 'HRV'),
('Cuba', 'CU', 'CUB'),
('Cyprus', 'CY', 'CYP'),
('Czech Republic', 'CZ', 'CZE'),
('Beni', 'BJ', 'BE'),
('Denmark', 'DK', 'DNK'),
('Dominica', 'DM', 'DMA'),
('Dominican Republic', 'DO', 'DOM'),
('Ecuador', 'EC', 'ECU'),
('El Salvador', 'SV', 'SLV'),
('Equatorial Guinea', 'GQ', 'GNQ'),
('Ethiopia', 'ET', 'ETH'),
('Eritrea', 'ER', 'ERI'),
('Estonia', 'EE', 'EST'),
('Faroe Islands', 'FO', 'FRO'),
('Falkland Islands (Malvinas)', 'FK', 'FLK'),
('South Georgia and the South Sandwich Islands', 'GS', 'SGS'),
('Fiji', 'FJ', 'FJI'),
('Finland', 'FI', 'FI'),
('Åland Islands', 'AX', 'ALA'),
('France', 'FR', 'FRA'),
('French Guiana', 'GF', 'GUF'),
('French Polynesia', 'PF', 'PYF'),
('French Southern Territories', 'TF', 'ATF'),
('Djibouti', 'DJ', 'DJI'),
('Gabo', 'GA', 'GAB'),
('Georgia', 'GE', 'GEO'),
('Gambia', 'GM', 'GMB'),
('Palestinian Territory, Occupied', 'PS', 'PSE'),
('Germany', 'DE', 'DEU'),
('Ghana', 'GH', 'GHA'),
('Gibraltar', 'GI', 'GIB'),
('Kiribati', 'KI', 'KIR'),
('Greece', 'GR', 'GRC'),
('Greenland', 'GL', 'GRL'),
('Grenada', 'GD', 'GRD'),
('Guadeloupe', 'GP', 'GLP'),
('Guam', 'GU', 'GUM'),
('Guatemala', 'GT', 'GTM'),
('Guinea', 'G', 'GI'),
('Guyana', 'GY', 'GUY'),
('Haiti', 'HT', 'HTI'),
('Heard Island and McDonald Islands', 'HM', 'HMD'),
('Holy See (Vatican City State)', 'VA', 'VAT'),
('Honduras', 'H', 'HND'),
('Hong Kong', 'HK', 'HKG'),
('Hungary', 'HU', 'HU'),
('Iceland', 'IS', 'ISL'),
('India', 'I', 'IND'),
('Indonesia', 'ID', 'ID'),
('Iran, Islamic Republic of', 'IR', 'IR'),
('Iraq', 'IQ', 'IRQ'),
('Ireland', 'IE', 'IRL'),
('Israel', 'IL', 'ISR'),
('Italy', 'IT', 'ITA'),
('Côte d''Ivoire', 'CI', 'CIV'),
('Jamaica', 'JM', 'JAM'),
('Japa', 'JP', 'JP'),
('Kazakhsta', 'KZ', 'KAZ'),
('Jorda', 'JO', 'JOR'),
('Kenya', 'KE', 'KE'),
('Korea, Democratic People''s Republic of', 'KP', 'PRK'),
('Korea, Republic of', 'KR', 'KOR'),
('Kuwait', 'KW', 'KWT'),
('Kyrgyzsta', 'KG', 'KGZ'),
('Lao People''s Democratic Republic', 'LA', 'LAO'),
('Lebano', 'LB', 'LB'),
('Lesotho', 'LS', 'LSO'),
('Latvia', 'LV', 'LVA'),
('Liberia', 'LR', 'LBR'),
('Libyan Arab Jamahiriya', 'LY', 'LBY'),
('Liechtenstei', 'LI', 'LIE'),
('Lithuania', 'LT', 'LTU'),
('Luxembourg', 'LU', 'LUX'),
('Macao', 'MO', 'MAC'),
('Madagascar', 'MG', 'MDG'),
('Malawi', 'MW', 'MWI'),
('Malaysia', 'MY', 'MYS'),
('Maldives', 'MV', 'MDV'),
('Mali', 'ML', 'MLI'),
('Malta', 'MT', 'MLT'),
('Martinique', 'MQ', 'MTQ'),
('Mauritania', 'MR', 'MRT'),
('Mauritius', 'MU', 'MUS'),

('Monaco', 'MC', 'MCO'),
('Monlia', 'M', 'MNG'),
('Moldova, Republic of', 'MD', 'MDA'),
('Montenegro', 'ME', 'MNE'),
('Montserrat', 'MS', 'MSR'),
('Morocco', 'MA', 'MAR'),
('Mozambique', 'MZ', 'MOZ'),
('Oma', 'OM', 'OM'),
('Namibia', 'NA', 'NAM'),
('Nauru', 'NR', 'NRU'),
('Nepal', 'NP', 'NPL'),
('Netherlands', 'NL', 'NLD'),
('Netherlands Antilles', 'A', 'ANT'),
('Curaçao', 'CW', 'CUW'),
('Aruba', 'AW', 'ABW'),
('Bonaire, Sint Eustatius and Saba', 'BQ', 'BES'),
('New Caledonia', 'NC', 'NCL'),
('Vanuatu', 'VU', 'VUT'),
('New Zealand', 'NZ', 'NZL'),
('Nicaragua', 'NI', 'NIC'),
('Niger', 'NE', 'NER'),
('Nigeria', 'NG', 'NGA'),
('Niue', 'NU', 'NIU'),
('Norfolk Island', 'NF', 'NFK'),
('Norway', 'NO', 'NOR'),
('Northern Mariana Islands', 'MP', 'MNP'),
('United States Minor Outlying Islands', 'UM', 'UMI'),
('Micronesia, Federated States of', 'FM', 'FSM'),
('Marshall Islands', 'MH', 'MHL'),
('Palau', 'PW', 'PLW'),
('Pakista', 'PK', 'PAK'),
('Panama', 'PA', 'PA'),
('Papua New Guinea', 'PG', 'PNG'),
('Paraguay', 'PY', 'PRY'),
('Peru', 'PE', 'PER'),
('Philippines', 'PH', 'PHL'),
('Pitcair', 'P', 'PC'),
('Poland', 'PL', 'POL'),
('Portugal', 'PT', 'PRT'),
('Guinea-Bissau', 'GW', 'GNB'),
('Timor-Leste', 'TL', 'TLS'),
('Puerto Rico', 'PR', 'PRI'),
('Qatar', 'QA', 'QAT'),
('Réunio', 'RE', 'REU'),
('Romania', 'RO', 'ROU'),
('Russian Federatio', 'RU', 'RUS'),
('Rwanda', 'RW', 'RWA'),
('Saint Barthélemy', 'BL', 'BLM'),
('Saint Helena, Ascension and Tristan da Cunha', 'SH', 'SH'),
('Saint Kitts and Nevis', 'K', 'KNA'),
('Anguilla', 'AI', 'AIA'),
('Saint Lucia', 'LC', 'LCA'),
('Saint Martin (French part)', 'MF', 'MAF'),
('Saint Pierre and Miquelo', 'PM', 'SPM'),
('Saint Vincent and the Grenadines', 'VC', 'VCT'),
('San Marino', 'SM', 'SMR'),
('Sao Tome and Principe', 'ST', 'STP'),
('Saudi Arabia', 'SA', 'SAU'),
('Senegal', 'S', 'SE'),
('Serbia', 'RS', 'SRB'),
('Seychelles', 'SC', 'SYC'),
('Sierra Leone', 'SL', 'SLE'),
('Singapore', 'SG', 'SGP'),
('Slovakia', 'SK', 'SVK'),
('Viet Nam', 'V', 'VNM'),
('Slovenia', 'SI', 'SV'),
('Somalia', 'SO', 'SOM'),
('South Africa', 'ZA', 'ZAF'),
('Zimbabwe', 'ZW', 'ZWE'),
('Spai', 'ES', 'ESP'),
('Western Sahara', 'EH', 'ESH'),
('Suda', 'SD', 'SD'),
('Suriname', 'SR', 'SUR'),
('Svalbard and Jan Maye', 'SJ', 'SJM'),
('Swaziland', 'SZ', 'SWZ'),
('Swede', 'SE', 'SWE'),
('Switzerland', 'CH', 'CHE'),
('Syrian Arab Republic', 'SY', 'SYR'),
('Tajikista', 'TJ', 'TJK'),
('Thailand', 'TH', 'THA'),
('To', 'TG', 'T'),
('Tokelau', 'TK', 'TKL'),
('Tonga', 'TO', 'TO'),
('Trinidad and Toba', 'TT', 'TTO'),
('United Arab Emirates', 'AE', 'ARE'),
('Tunisia', 'T', 'TU'),
('Turkey', 'TR', 'TUR'),
('Turkmenista', 'TM', 'TKM'),
('Turks and Caicos Islands', 'TC', 'TCA'),
('Tuvalu', 'TV', 'TUV'),
('Uganda', 'UG', 'UGA'),
('Ukraine', 'UA', 'UKR'),
('Macedonia, the former Yuslav Republic of', 'MK', 'MKD'),
('Egypt', 'EG', 'EGY'),
('United Kingdom', 'GB', 'GBR'),
('Guernsey', 'GG', 'GGY'),
('Jersey', 'JE', 'JEY'),
('Isle of Ma', 'IM', 'IM'),
('Tanzania, United Republic of', 'TZ', 'TZA'),
('United States', 'US', 'USA'),
('Virgin Islands, U.S.', 'VI', 'VIR'),
('Burkina Faso', 'BF', 'BFA'),
('Uruguay', 'UY', 'URY'),
('Uzbekista', 'UZ', 'UZB'),
('Venezuela, Bolivarian Republic of', 'VE', 'VE'),
('Wallis and Futuna', 'WF', 'WLF'),
('Samoa', 'WS', 'WSM'),
('Yeme', 'YE', 'YEM'),
('Zambia', 'ZM', 'ZMB')
