SET IDENTITY_INSERT RegionA ON
INSERT INTO RegionA(RegionId,CountryId,name,description) VALUES
(09,1,'Distrito Federal','Distrito Federal')
,(01,1,'Aguascalientes','Aguascalientes')
,(02,1,'Baja California','Baja California')
,(03,1,'Baja California Sur','Baja California Sur')
,(04,1,'Campeche','Campeche')
,(05,1,'Coahuila de Zaragoza','Coahuila de Zaragoza')
,(06,1,'Colima','Colima')
,(07,1,'Chiapas','Chiapas')
,(08,1,'Chihuahua','Chihuahua')
,(10,1,'Durango','Durango')
,(11,1,'Guanajuato','Guanajuato')
,(12,1,'Guerrero','Guerrero')
,(13,1,'Hidalgo','Hidalgo')
,(14,1,'Jalisco','Jalisco')
,(15,1,'México','México')
,(16,1,'Michoacán de Ocampo','Michoacán de Ocampo')
,(17,1,'Morelos','Morelos')
,(18,1,'Nayarit','Nayarit')
,(19,1,'Nuevo León','Nuevo León')
,(20,1,'Oaxaca','Oaxaca')
,(21,1,'Puebla','Puebla')
,(22,1,'Querétaro','Querétaro')
,(23,1,'Quintana Roo','Quintana Roo')
,(24,1,'San Luis Potosí','San Luis Potosí')
,(25,1,'Sinaloa','Sinaloa')
,(26,1,'Sonora','Sonora')
,(27,1,'Tabasco','Tabasco')
,(28,1,'Tamaulipas','Tamaulipas')
,(29,1,'Tlaxcala','Tlaxcala')
,(30,1,'Veracruz de Ignacio de la Llave','Veracruz de Ignacio de la Llave')
,(31,1,'Yucatán','Yucatán')
,(32,1,'Zacatecas','Zacatecas');
SET IDENTITY_INSERT RegionA OFF