//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drs.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.ClientPhone = new HashSet<ClientPhone>();
            this.OrderToStore = new HashSet<OrderToStore>();
            this.FranchiseStore = new HashSet<FranchiseStore>();
        }
    
        public int AddressId { get; set; }
        public string MainAddress { get; set; }
        public string ExtIntNumber { get; set; }
        public string Reference { get; set; }
        public int CountryId { get; set; }
        public Nullable<int> RegionArId { get; set; }
        public Nullable<int> RegionBrId { get; set; }
        public Nullable<int> RegionCrId { get; set; }
        public Nullable<int> RegionDrId { get; set; }
        public Nullable<int> ZipCodeId { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual RegionA RegionA { get; set; }
        public virtual RegionB RegionB { get; set; }
        public virtual RegionC RegionC { get; set; }
        public virtual RegionD RegionD { get; set; }
        public virtual ZipCode ZipCode { get; set; }
        public virtual ICollection<ClientPhone> ClientPhone { get; set; }
        public virtual ICollection<OrderToStore> OrderToStore { get; set; }
        public virtual ICollection<FranchiseStore> FranchiseStore { get; set; }
    }
}
