//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drs.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetMenu
    {
        public AspNetMenu()
        {
            this.AspNetMenu1 = new HashSet<AspNetMenu>();
            this.AspNetMenuRole = new HashSet<AspNetMenuRole>();
        }
    
        public int AspNetMenuId { get; set; }
        public int Position { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Area { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string Title { get; set; }
        public string Icon { get; set; }
        public bool IsObsolete { get; set; }
    
        public virtual ICollection<AspNetMenu> AspNetMenu1 { get; set; }
        public virtual AspNetMenu AspNetMenu2 { get; set; }
        public virtual ICollection<AspNetMenuRole> AspNetMenuRole { get; set; }
    }
}
