//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drs.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallCenterInfo
    {
        public CallCenterInfo()
        {
            this.ServerInfo = new HashSet<ServerInfo>();
            this.ClientInfo = new HashSet<ClientInfo>();
        }
    
        public int CallCenterInfoId { get; set; }
        public string ActivationCode { get; set; }
    
        public virtual ICollection<ServerInfo> ServerInfo { get; set; }
        public virtual ICollection<ClientInfo> ClientInfo { get; set; }
    }
}
