//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drs.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryMessage
    {
        public CategoryMessage()
        {
            this.StoreMessageDate = new HashSet<StoreMessageDate>();
        }
    
        public int CategoryMessageId { get; set; }
        public string Category { get; set; }
        public string Color { get; set; }
        public string Description { get; set; }
        public int Position { get; set; }
    
        public virtual ICollection<StoreMessageDate> StoreMessageDate { get; set; }
    }
}
