//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drs.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatPayment
    {
        public CatPayment()
        {
            this.OrderToStore = new HashSet<OrderToStore>();
        }
    
        public int CatPaymentId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsObsolete { get; set; }
    
        public virtual ICollection<OrderToStore> OrderToStore { get; set; }
    }
}
