//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drs.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientPhone
    {
        public ClientPhone()
        {
            this.ClientPhoneStatistics = new HashSet<ClientPhoneStatistics>();
            this.OrderToStore = new HashSet<OrderToStore>();
            this.Address = new HashSet<Address>();
            this.Client = new HashSet<Client>();
        }
    
        public long ClientPhoneId { get; set; }
        public string Phone { get; set; }
        public string UserIdIns { get; set; }
        public string UserIdUpd { get; set; }
        public System.DateTime DatetimeIns { get; set; }
        public Nullable<System.DateTime> DatetimeUpd { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual ICollection<ClientPhoneStatistics> ClientPhoneStatistics { get; set; }
        public virtual ICollection<OrderToStore> OrderToStore { get; set; }
        public virtual ICollection<Address> Address { get; set; }
        public virtual ICollection<Client> Client { get; set; }
    }
}
