//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drs.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlTitle
    {
        public int AddressTitleId { get; set; }
        public string Container { get; set; }
        public string ControlName { get; set; }
        public int LanguageId { get; set; }
        public string Name { get; set; }
        public bool IsEnabled { get; set; }
    }
}
