//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drs.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FranchiseStoreGeoMap
    {
        public int FranchiseStoreGeoMapId { get; set; }
        public int FranchiseStoreId { get; set; }
        public System.Data.Entity.Spatial.DbGeography Coverage { get; set; }
    
        public virtual FranchiseStore FranchiseStore { get; set; }
    }
}
