//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drs.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FranchiseButton
    {
        public int FranchiseId { get; set; }
        public int Position { get; set; }
        public string Color { get; set; }
        public string Image { get; set; }
        public string Products { get; set; }
    
        public virtual Franchise Franchise { get; set; }
    }
}
