//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drs.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoClientTerminal
    {
        public InfoClientTerminal()
        {
            this.InfoClientTerminalVersion = new HashSet<InfoClientTerminalVersion>();
        }
    
        public int InfoClientTerminalId { get; set; }
        public string Host { get; set; }
        public string Code { get; set; }
        public Nullable<int> InfoCallCenterId { get; set; }
    
        public virtual InfoCallCenter InfoCallCenter { get; set; }
        public virtual ICollection<InfoClientTerminalVersion> InfoClientTerminalVersion { get; set; }
    }
}
