//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drs.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoCallCenter
    {
        public InfoCallCenter()
        {
            this.InfoClientTerminal = new HashSet<InfoClientTerminal>();
            this.InfoServer = new HashSet<InfoServer>();
        }
    
        public int InfoCallCenterId { get; set; }
        public string ActivationCode { get; set; }
    
        public virtual ICollection<InfoClientTerminal> InfoClientTerminal { get; set; }
        public virtual ICollection<InfoServer> InfoServer { get; set; }
    }
}
