//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drs.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoClientTerminalFranchise
    {
        public int InfoClientTerminalFranchiseId { get; set; }
        public int InfoClientTerminalId { get; set; }
        public int FranchiseId { get; set; }
        public string PosIpAddress { get; set; }
    
        public virtual Franchise Franchise { get; set; }
        public virtual InfoClientTerminal InfoClientTerminal { get; set; }
    }
}
