//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drs.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        public Module()
        {
            this.Permission = new HashSet<Permission>();
        }
    
        public int ModuleId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Code { get; set; }
        public System.DateTime InsertDate { get; set; }
        public string Parameters { get; set; }
        public bool IsObsolete { get; set; }
    
        public virtual MenuModule MenuModule { get; set; }
        public virtual ICollection<Permission> Permission { get; set; }
    }
}
