//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drs.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PosOrder
    {
        public PosOrder()
        {
            this.PosOrderItem = new HashSet<PosOrderItem>();
            this.OrderToStore = new HashSet<OrderToStore>();
        }
    
        public int PosOrderId { get; set; }
        public string FranchiseCode { get; set; }
        public int CheckId { get; set; }
        public System.Guid GuidId { get; set; }
        public System.DateTime OrderDatetime { get; set; }
        public string UserId { get; set; }
        public decimal Subtotal { get; set; }
        public decimal Taxes { get; set; }
        public decimal Total { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual ICollection<PosOrderItem> PosOrderItem { get; set; }
        public virtual ICollection<OrderToStore> OrderToStore { get; set; }
    }
}
