//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drs.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recurrence
    {
        public int RecurrenceId { get; set; }
        public int ClientId { get; set; }
        public long OrderToStoreId { get; set; }
        public System.DateTime Timestamp { get; set; }
        public long TimestampShort { get; set; }
        public decimal Total { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual OrderToStore OrderToStore { get; set; }
    }
}
