//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drs.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource
    {
        public Resource()
        {
            this.FranchiseButton = new HashSet<FranchiseButton>();
        }
    
        public int ResourceId { get; set; }
        public string OriginalName { get; set; }
        public string CurrentPath { get; set; }
        public string UidFileName { get; set; }
        public System.DateTime UploadDateTime { get; set; }
        public bool IsObsolete { get; set; }
        public int FileType { get; set; }
        public string UploadUserId { get; set; }
        public string CheckSum { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual ICollection<FranchiseButton> FranchiseButton { get; set; }
    }
}
