//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drs.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int SettingId { get; set; }
        public string GroupName { get; set; }
        public string KeyName { get; set; }
        public string Value { get; set; }
        public string Description { get; set; }
    }
}
