//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drs.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreMessage
    {
        public StoreMessage()
        {
            this.StoreMessageDate = new HashSet<StoreMessageDate>();
        }
    
        public int StoreMessageId { get; set; }
        public string Message { get; set; }
        public string UserIdIns { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual ICollection<StoreMessageDate> StoreMessageDate { get; set; }
    }
}
