//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drs.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreAddressDistribution
    {
        public int StoreAddressDistributionId { get; set; }
        public int FranchiseStoreId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> RegionArId { get; set; }
        public Nullable<int> RegionBrId { get; set; }
        public Nullable<int> RegionCrId { get; set; }
        public Nullable<int> RegionDrId { get; set; }
        public Nullable<int> ZipCodeId { get; set; }
        public int Importance { get; set; }
    
        public virtual FranchiseStore FranchiseStore { get; set; }
    }
}
