//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drs.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreStatus
    {
        public int FranchiseStoreId { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> LastDatetime { get; set; }
        public Nullable<long> LastOrderToStoreId { get; set; }
        public int MaxCapacity { get; set; }
    
        public virtual FranchiseStore FranchiseStore { get; set; }
        public virtual OrderToStore OrderToStore { get; set; }
    }
}
