//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drs.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreMessageDate
    {
        public long StoreMessageDateId { get; set; }
        public int CategoryMessageId { get; set; }
        public int StoreMessageId { get; set; }
        public int FranchiseStoreId { get; set; }
        public System.DateTime DateApplied { get; set; }
        public string UserIdIns { get; set; }
        public bool IsIndefinite { get; set; }
        public string Resource { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual CategoryMessage CategoryMessage { get; set; }
        public virtual StoreMessage StoreMessage { get; set; }
        public virtual FranchiseStore FranchiseStore { get; set; }
    }
}
