//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drs.Repository.Entities
{
    using System;
    
    public partial class ufnGetFrequentClientByRangeDates_Result1
    {
        public string FullName { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Email { get; set; }
        public string LoyaltyCode { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> TotalByConsume { get; set; }
        public string StoreName { get; set; }
        public string FranchiseName { get; set; }
    }
}
