//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drs.Repository.Entities
{
    using System;
    
    public partial class ufnGetTopProductsByRangeDates_Result1
    {
        public string ProductName { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> TotalByProduct { get; set; }
        public int FranchiseStoreId { get; set; }
        public string StoreName { get; set; }
        public string FranchiseName { get; set; }
    }
}
