//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drs.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewStoreInfo
    {
        public int FranchiseStoreId { get; set; }
        public string Name { get; set; }
        public string FranchiseName { get; set; }
        public string Address { get; set; }
        public string WsAddress { get; set; }
        public string ManagerUser { get; set; }
        public string ManagerUserId { get; set; }
        public bool IsObsolete { get; set; }
    }
}
