//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drs.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewOrderInfo
    {
        public long OrderToStoreId { get; set; }
        public string FranchiseName { get; set; }
        public string FranchiseStoreName { get; set; }
        public System.DateTime StartDatetime { get; set; }
        public string LastStatus { get; set; }
        public string Phone { get; set; }
        public string FullName { get; set; }
        public string Address { get; set; }
        public decimal Total { get; set; }
        public string UserName { get; set; }
    }
}
