//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drs.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewAgentSales
    {
        public string FullName { get; set; }
        public string LastStatus { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> SalesPerDay { get; set; }
        public Nullable<decimal> TotalPerDay { get; set; }
        public int FranchiseStoreId { get; set; }
        public string FranchiseStore { get; set; }
        public string Franchise { get; set; }
    }
}
