//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drs.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewPosOrderInfo
    {
        public int FranchiseId { get; set; }
        public int FranchiseStoreId { get; set; }
        public long OrderToStoreId { get; set; }
        public System.DateTime FirstDatetime { get; set; }
        public long ItemId { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
    }
}
