//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drs.Repository.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewClientOrderInfoByFranchiseStore
    {
        public int FranchiseId { get; set; }
        public string FranchiseName { get; set; }
        public int FranchiseStoreId { get; set; }
        public string FranchiseStoreName { get; set; }
        public long ClientId { get; set; }
        public string Phone { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public long OrderToStoreId { get; set; }
        public string OrderAtoId { get; set; }
        public System.DateTime FirstDatetime { get; set; }
        public string LastStatus { get; set; }
        public decimal Total { get; set; }
    }
}
